/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Web CSRF cookie başlatma
         * @description Girişten önce çağrılır. Cookie saklanır; XSRF-TOKEN değeri X-XSRF-TOKEN başlığında gönderilir.
         */
        get: operations["csrfCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bireysel hesap ve kişisel bağlam oluşturma
         * @description Rol, tenant ve doğrulama alanları gönderilemez. Otomatik giriş yapılmaz; doğrulama e-postası kuyruğa alınır.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Web cookie oturumu açma
         * @description CSRF gerekir. Token döndürmez; session ID yenilenir.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mobile-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cihaz bazlı süreli mobil token
         * @description Aynı device_id önceki tokenı iptal eder. Süre üst sınırı yedi gündür; aktif hesap gerekir.
         */
        post: operations["mobileToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Geçerli oturumu kapatma
         * @description Geçerli oturumu kapatma
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parola sıfırlama talebi
         * @description Hesabın bulunup bulunmadığını açıklamayan ortak yanıt.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parolayı sıfırlama ve oturumları iptal etme
         * @description Parolayı sıfırlama ve oturumları iptal etme
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-verification-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Doğrulama e-postasını tekrar gönderme
         * @description Doğrulama e-postasını tekrar gönderme
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/{id}/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * İmzalı bağlantıyla e-posta doğrulama
         * @description Giriş yapmış aynı kullanıcı, geçerli signature ve expires gerektirir.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kendi profilini okuma
         * @description Kendi profilini okuma
         */
        get: operations["profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Kendi adını güncelleme
         * @description E-posta, parola, sahiplik ve yetki alanlarının bu uçtan değişimi reddedilir.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/me/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kendi kişisel ve aktif kurum bağlamları
         * @description Doğrulanmış e-posta gerekir; iptal üyelikleri ve kapalı kurumlar listelenmez.
         */
        get: operations["contexts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kendi yetkili çalışma bağlamını okuma
         * @description Başkalarının kişisel veya kurum çalışma bağlamı okunamaz; kurum yöneticisi de bu uçtan öğrenci bağlamına erişemez.
         */
        get: operations["context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform yöneticisi kurum listesi
         * @description Platform yöneticisi kurum listesi
         */
        get: operations["listTenants"];
        put?: never;
        /**
         * Platform yöneticisi kurum oluşturma
         * @description Platform yöneticisi kurum oluşturma
         */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yetkili kurum profili
         * @description Aktif kurum yöneticisi veya platform yöneticisi gerekir.
         */
        get: operations["tenantProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kurum üyelerini kapsamlı listeleme
         * @description Aktif kurum yöneticisi/platform yöneticisi; yalnız bu kuruma ait üyeler. Kişisel geçmiş veya diğer üyelikler döndürülmez.
         */
        get: operations["listMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant}/memberships/{membership}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kurum içinden tek üyelik okuma
         * @description Kurum içinden tek üyelik okuma
         */
        get: operations["membership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Platform yöneticisi üyelik oluşturma
         * @description Aktif kullanıcı ve kurum gerekir; kurum yöneticisi bu uçla yetki veremez. tenant_id body içinde reddedilir.
         */
        post: operations["createMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant}/memberships/{membership}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Platform yöneticisi üyelik iptali
         * @description Üyeliği ve geçmiş bağlamını silmez; sonraki erişimi engeller. Tekrar aynı talep güvenlidir.
         */
        delete: operations["revokeMembership"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform yöneticisi ders listesi
         * @description Platform yöneticisi ders listesi
         */
        get: operations["adminListSubjects"];
        put?: never;
        /**
         * Merkezi ders kaydı oluşturma
         * @description Merkezi ders kaydı oluşturma
         */
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform yöneticisi konu listesi
         * @description Platform yöneticisi konu listesi
         */
        get: operations["adminListTopics"];
        put?: never;
        /**
         * Merkezi konu kaydı oluşturma
         * @description Merkezi konu kaydı oluşturma
         */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform yöneticisi sınav türü listesi
         * @description Platform yöneticisi sınav türü listesi
         */
        get: operations["adminListExamTypes"];
        put?: never;
        /**
         * Merkezi sınav türü kaydı oluşturma
         * @description Merkezi sınav türü kaydı oluşturma
         */
        post: operations["createExamType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/question-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform yöneticisi kaynak listesi
         * @description Platform yöneticisi kaynak listesi
         */
        get: operations["adminListQuestionSources"];
        put?: never;
        /**
         * Merkezi kaynak kaydı oluşturma
         * @description Merkezi kaynak kaydı oluşturma
         */
        post: operations["createQuestionSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkezi sınıflandırma listesi
         * @description Doğrulanmış aktif kullanıcılara açık sınıflandırmalar. Taslak soru içerikleri içermez. Ders/konu etiketleri henüz soru yayımlanmadan da listelenebilir.
         */
        get: operations["listSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exam-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkezi sınıflandırma listesi
         * @description Doğrulanmış aktif kullanıcılara açık sınıflandırmalar. Taslak soru içerikleri içermez. Ders/konu etiketleri henüz soru yayımlanmadan da listelenebilir.
         */
        get: operations["listExamTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkezi sınıflandırma listesi
         * @description Doğrulanmış aktif kullanıcılara açık sınıflandırmalar. Taslak soru içerikleri içermez. Ders/konu etiketleri henüz soru yayımlanmadan da listelenebilir.
         */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merkezi soruları son taslaklarına göre listeleme
         * @description Merkezi soruları son taslaklarına göre listeleme
         */
        get: operations["adminListQuestions"];
        put?: never;
        /**
         * Soru kimliği ve ilk taslak sürümü oluşturma
         * @description Tek doğru seçenekli metin sorusu. Seçenek sırası dizi sırasıdır; doğru cevap konumu 1 tabanlıdır. Kaynak ve cevap taslakta eksik olabilir. tenant/sahip/yayın alanları kabul edilmez.
         */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{question}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sorunun son taslağı ve yayın durumunu görüntüleme
         * @description Sorunun son taslağı ve yayın durumunu görüntüleme
         */
        get: operations["adminShowQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Yeni taslak soru sürümü oluşturma
         * @description İçerik tam snapshot olarak gönderilir; atlanan nullable alanlar yeni sürümde null olur. base_version soru revision değeridir. Satır kilidi altında farklı revision 409 üretir. Mevcut yayındaki içerik değiştirilmez.
         */
        patch: operations["reviseQuestion"];
        trace?: never;
    };
    "/api/v1/admin/questions/{question}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Son taslak soru sürümünü yayımlama
         * @description En az iki seçenek, kaynak ve bir doğru cevap zorunludur. base_version güncel revision olmalıdır. Güncel yayın tekrar gönderildiğinde revision/audit çoğalmaz; eski revision ile tekrar 409 verir.
         */
        post: operations["publishQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{question}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Soru sürümlerinin yönetici geçmişi
         * @description Soru sürümlerinin yönetici geçmişi
         */
        get: operations["listQuestionVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yayımlanmış soruları filtreleyip listeleme
         * @description Filtreler yayımlanmış sürüme uygulanır; taslaklar, cevap anahtarı ve açıklama dönmez. topic_id yalnız tam konu eşleşmesidir.
         */
        get: operations["listPublishedQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{question}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Güncel yayımlanmış soruyu görüntüleme
         * @description Taslak veya mevcut olmayan soru 404 döner. Cevap anahtarı ve açıklama bu route üzerinde dönmez; tek soru alıştırması Study uçlarıyla değerlendirilir.
         */
        get: operations["showPublishedQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/practice-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kendi bağlamında çözüm geçmişi
         * @description Yalnız bağlam sahibi ve aktif üyelik erişebilir; kurum yöneticisi başka öğrencinin geçmişini okuyamaz. Başlanmış çalışmalar da listelenir; created_at/id ile cursor sırası.
         */
        get: operations["listPracticeAttempts"];
        put?: never;
        /**
         * Yayımlanmış soru sürümüne sabit alıştırma açma
         * @description İstemci UUID id aynı içerikle tekrar kullanılınca aynı çözüm döner (200). Farklı içerik veya bağlam 409. question_version_id güncel yayımlanmış sürümle uyuşmalıdır; değiştiyse question_changed 409. Başlanmış çalışmada cevap anahtarı/açıklama gizlidir.
         */
        post: operations["startPracticeAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/practice-attempts/{attempt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sabit sürümü ve varsa çözüm sonucunu okuma
         * @description Soru sonradan yayımlansa bile bu çalışmanın sürümü değişmez. Başka bağlamın çalışması 404 döner.
         */
        get: operations["showPracticeAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/practice-attempts/{attempt}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tek soruyu sunucuda değerlendirme
         * @description selected_option_id bu sürümün seçeneği veya açıkça null (boş bırakma) olmalıdır. Aynı cevap tekrarında aynı sonuç; tamamlandıktan sonra farklı cevap answer_locked 409. Nihai cevap/açıklama yalnız cevaplandıktan sonra bu kayıtta görünür. Resmî sınav puanlama veya süre kuralı değildir.
         */
        post: operations["answerPracticeAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/exam-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bağlama ait süreli deneme geçmişi
         * @description Süresi dolan kayıtları tamamlar. started_at/id ile cursor sırası; yalnız sahibi ve aktif üyelik.
         */
        get: operations["listExams"];
        put?: never;
        /**
         * Rastgele yayımlanmış sorularla süreli çalışma başlatma
         * @description UUID id ve aynı ayarlar tekrarında aynı deneme. Farklı ayarlar/bağlam 409; yetersiz havuz 422. Sorular başlangıç sürümüne sabitlenir. Kullanıcının seçtiği süre ve doğru yüzdesi çalışma amaçlıdır; resmî sınav şablonu değildir.
         */
        post: operations["startExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/exam-attempts/{exam}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Denemeyi sürdürme veya sonucu okuma
         * @description Sunucu zamanı ve son süre döner. Süre dolduysa atomik olarak tamamlanır. Cevap anahtarı yalnız tamamlanınca görünür.
         */
        get: operations["showExam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/exam-attempts/{exam}/answers/{answer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Süre içinde deneme cevabını kaydetme veya değiştirme
         * @description base_version güncel revision olmalıdır; aynı kaydedilmiş cevap tekrarı eski revision ile de güvenlidir. Farklı eski cevap 409 version_conflict. null cevabı temizler. Biten/süresi dolan denemeye geç gelen yazı değiştirilmez; tamamlanmış kayıt 200 döner.
         */
        put: operations["saveExamAnswer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contexts/{context}/exam-attempts/{exam}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tüm cevapları tek işlemde değerlendirme
         * @description Güncel base_version gerekir; eski revision 409. Boşlar dahil sabit sürümlerden doğru/yanlış/boş ve doğru yüzdesi hesaplanır. Bitirme tekrarı aynı değişmez sonucu döndürür. Süreyi sunucu belirler.
         */
        post: operations["finishExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            email_verified_at: string | null;
            /** @enum {string} */
            platform_role: "student" | "platform_admin";
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            status: "active" | "inactive";
        };
        MemberUser: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        Context: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "personal" | "tenant";
            /** Format: uuid */
            tenant_id: string | null;
            /** Format: uuid */
            membership_id: string | null;
            name: string;
            /** @enum {string|null} */
            role: "student" | "company_admin" | null;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "student" | "company_admin";
            /** @enum {string} */
            status: "active" | "revoked";
            /** Format: date-time */
            joined_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            user: components["schemas"]["MemberUser"];
        };
        Message: {
            message: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            /** Format: uuid */
            request_id: string;
            errors?: {
                [key: string]: string[];
            };
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegistrationInput: {
            name: string;
            /** Format: email */
            email: string;
            /** @description En az bir büyük harf, küçük harf, rakam ve sembol içerir. */
            password: string;
            password_confirmation: string;
        };
        MobileTokenInput: components["schemas"]["LoginInput"] & {
            /** Format: uuid */
            device_id: string;
        };
        ForgotInput: {
            /** Format: email */
            email: string;
        };
        ResetInput: {
            /** Format: email */
            email: string;
            token: string;
            /** @description Büyük/küçük harf, rakam ve sembol gerekir. */
            password: string;
            password_confirmation: string;
        };
        ProfileInput: {
            name: string;
        };
        TenantInput: {
            name: string;
            slug: string;
        };
        MembershipInput: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "student" | "company_admin";
        };
        MobileToken: {
            /** @description Yalnız bu yanıtla verilir; güvenli cihaz deposuna yazılır. */
            token: string;
            /** @constant */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        TenantResponse: {
            data: components["schemas"]["Tenant"];
        };
        MembershipResponse: {
            data: components["schemas"]["Membership"];
        };
        MessageResponse: {
            data: components["schemas"]["Message"];
        };
        MobileTokenResponse: {
            data: components["schemas"]["MobileToken"];
        };
        ContextResponse: {
            data: components["schemas"]["Context"];
        };
        TenantList: {
            data: components["schemas"]["Tenant"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        MembershipList: {
            data: components["schemas"]["Membership"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        ContextList: {
            data: components["schemas"]["Context"][];
        };
        Subject: {
            /** Format: uuid */
            id: string;
            name: string;
            code: string;
        };
        Topic: {
            /** Format: uuid */
            id: string;
            name: string;
            code: string;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            parent_id: string | null;
        };
        ExamType: {
            /** Format: uuid */
            id: string;
            name: string;
            code: string;
        };
        QuestionSource: {
            /** Format: uuid */
            id: string;
            title: string;
            url: string | null;
            citation: string | null;
        };
        QuestionOption: {
            /** Format: uuid */
            id: string;
            position: number;
            text: string;
        };
        QuestionVersion: {
            /** Format: uuid */
            id: string;
            version: number;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            topic_id: string | null;
            /** Format: uuid */
            exam_type_id: string | null;
            stem: string;
            /** Format: date-time */
            published_at: string | null;
            source: components["schemas"]["QuestionSource"] | null;
            options: components["schemas"]["QuestionOption"][];
        };
        AdminQuestionVersion: {
            /** Format: uuid */
            id: string;
            version: number;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            topic_id: string | null;
            /** Format: uuid */
            exam_type_id: string | null;
            stem: string;
            /** Format: date-time */
            published_at: string | null;
            source: components["schemas"]["QuestionSource"] | null;
            options: components["schemas"]["QuestionOption"][];
            /** Format: uuid */
            correct_option_id: string | null;
            explanation: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Question: {
            /** Format: uuid */
            id: string;
            version: components["schemas"]["QuestionVersion"];
        };
        AdminQuestion: {
            /** Format: uuid */
            id: string;
            revision: number;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: uuid */
            published_version_id: string | null;
            has_pending_changes: boolean;
            latest_version: components["schemas"]["AdminQuestionVersion"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SubjectResponse: {
            data: components["schemas"]["Subject"];
        };
        SubjectList: {
            data: components["schemas"]["Subject"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        TopicResponse: {
            data: components["schemas"]["Topic"];
        };
        TopicList: {
            data: components["schemas"]["Topic"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        ExamTypeResponse: {
            data: components["schemas"]["ExamType"];
        };
        ExamTypeList: {
            data: components["schemas"]["ExamType"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        QuestionSourceResponse: {
            data: components["schemas"]["QuestionSource"];
        };
        QuestionSourceList: {
            data: components["schemas"]["QuestionSource"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        QuestionResponse: {
            data: components["schemas"]["Question"];
        };
        QuestionList: {
            data: components["schemas"]["Question"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        AdminQuestionResponse: {
            data: components["schemas"]["AdminQuestion"];
        };
        AdminQuestionList: {
            data: components["schemas"]["AdminQuestion"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        AdminQuestionVersionList: {
            data: components["schemas"]["AdminQuestionVersion"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        SubjectInput: {
            name: string;
            code: string;
        };
        ExamTypeInput: {
            name: string;
            code: string;
        };
        TopicInput: {
            name: string;
            code: string;
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        QuestionSourceInput: {
            title: string;
            url?: string | null;
            citation?: string | null;
        };
        QuestionInput: {
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            topic_id?: string | null;
            /** Format: uuid */
            exam_type_id?: string | null;
            /** Format: uuid */
            source_id?: string | null;
            stem: string;
            explanation?: string | null;
            options: string[];
            correct_option_position?: number | null;
        };
        QuestionUpdateInput: {
            /** Format: uuid */
            subject_id: string;
            /** Format: uuid */
            topic_id?: string | null;
            /** Format: uuid */
            exam_type_id?: string | null;
            /** Format: uuid */
            source_id?: string | null;
            stem: string;
            explanation?: string | null;
            options: string[];
            correct_option_position?: number | null;
            base_version: number;
        };
        QuestionPublishInput: {
            base_version: number;
        };
        CursorLinks: {
            /** Format: uri */
            first: string | null;
            /** Format: uri */
            last: string | null;
            /** Format: uri */
            prev: string | null;
            /** Format: uri */
            next: string | null;
        };
        CursorMeta: {
            /** Format: uri */
            path: string;
            per_page: number;
            next_cursor: string | null;
            prev_cursor: string | null;
        };
        StartPracticeInput: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            question_id: string;
            /** Format: uuid */
            question_version_id: string;
        };
        AnswerPracticeInput: {
            /** Format: uuid */
            selected_option_id: string | null;
        };
        PracticeFeedback: {
            /** Format: uuid */
            correct_option_id: string;
            explanation: string | null;
        };
        PracticeAttempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            context_id: string;
            /** Format: uuid */
            question_id: string;
            question: components["schemas"]["QuestionVersion"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            answered_at: string | null;
            /** Format: uuid */
            selected_option_id: string | null;
            /** @enum {string} */
            outcome: "pending" | "correct" | "incorrect" | "skipped";
            feedback: components["schemas"]["PracticeFeedback"] | null;
        };
        PracticeAttemptResponse: {
            data: components["schemas"]["PracticeAttempt"];
        };
        PracticeAttemptList: {
            data: components["schemas"]["PracticeAttempt"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        ExamResult: {
            correct: number;
            incorrect: number;
            blank: number;
            score_percent: number;
            elapsed_seconds: number;
        };
        ExamSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            context_id: string;
            revision: number;
            /** @enum {string} */
            status: "active" | "completed";
            question_count: number;
            duration_seconds: number;
            /** Format: uuid */
            subject_id: string | null;
            /** Format: uuid */
            topic_id: string | null;
            /** @enum {string} */
            scoring_rule: "correct_ratio_v1";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            deadline_at: string;
            /** Format: date-time */
            server_time: string;
            /** Format: date-time */
            finished_at: string | null;
            /** @enum {string|null} */
            finish_reason: "manual" | "expired" | null;
            result: components["schemas"]["ExamResult"] | null;
        };
        ExamQuestion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            question_id: string;
            position: number;
            question: components["schemas"]["QuestionVersion"];
            /** Format: uuid */
            selected_option_id: string | null;
            feedback: components["schemas"]["ExamFeedback"] | null;
        };
        ExamAttempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            context_id: string;
            revision: number;
            /** @enum {string} */
            status: "active" | "completed";
            question_count: number;
            duration_seconds: number;
            /** Format: uuid */
            subject_id: string | null;
            /** Format: uuid */
            topic_id: string | null;
            /** @enum {string} */
            scoring_rule: "correct_ratio_v1";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            deadline_at: string;
            /** Format: date-time */
            server_time: string;
            /** Format: date-time */
            finished_at: string | null;
            /** @enum {string|null} */
            finish_reason: "manual" | "expired" | null;
            result: components["schemas"]["ExamResult"] | null;
            questions: components["schemas"]["ExamQuestion"][];
        };
        ExamAttemptResponse: {
            data: components["schemas"]["ExamAttempt"];
        };
        ExamAttemptList: {
            data: components["schemas"]["ExamSummary"][];
            links: components["schemas"]["CursorLinks"];
            meta: components["schemas"]["CursorMeta"];
        };
        StartExamInput: {
            /** Format: uuid */
            id: string;
            question_count: number;
            duration_seconds: number;
            /** Format: uuid */
            subject_id?: string | null;
            /** Format: uuid */
            topic_id?: string | null;
        };
        SaveExamAnswerInput: {
            /** Format: uuid */
            selected_option_id: string | null;
            base_version: number;
        };
        FinishExamInput: {
            base_version: number;
        };
        ExamFeedback: {
            /** Format: uuid */
            correct_option_id: string;
            explanation: string | null;
            /** @enum {string} */
            outcome: "correct" | "incorrect" | "skipped";
        };
    };
    responses: {
        /** @description Türkçe problem ayrıntısı. 429 yanıtında Retry-After bulunur. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrfCookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    mobileToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MobileTokenInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileTokenResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                id: string;
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    contexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    context: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    tenantProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listMemberships: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    membership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                membership: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    revokeMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                membership: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminListSubjects: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminListTopics: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
                subject_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminListExamTypes: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTypeList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createExamType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamTypeInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTypeResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminListQuestionSources: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSourceList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createQuestionSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionSourceInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSourceResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listSubjects: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listExamTypes: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamTypeList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listTopics: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminListQuestions: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
                subject_id?: string;
                topic_id?: string;
                exam_type_id?: string;
                source_id?: string;
                status?: "draft" | "published";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    adminShowQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    reviseQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdateInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    publishQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionPublishInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listQuestionVersions: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                question: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQuestionVersionList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listPublishedQuestions: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
                subject_id?: string;
                topic_id?: string;
                exam_type_id?: string;
                source_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    showPublishedQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listPracticeAttempts: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                context: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAttemptList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    startPracticeAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartPracticeInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    showPracticeAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
                attempt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    answerPracticeAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
                attempt: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerPracticeInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listExams: {
        parameters: {
            query?: {
                per_page?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                context: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    startExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExamInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    showExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
                exam: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    saveExamAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
                exam: string;
                answer: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveExamAnswerInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    finishExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context: string;
                exam: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishExamInput"];
            };
        };
        responses: {
            /** @description Başarılı işlem. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamAttemptResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
}
