import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { cursorFromLink } from '@oggaq/api-client';
import { api, loadCatalogs } from '../api';
import { ErrorNotice, Icon, Loading, Status, dateLabel } from '../ui';

export function QuestionList() {
  const [subject, setSubject] = useState('');
  const [status, setStatus] = useState<'' | 'draft' | 'published'>('');
  const [cursor, setCursor] = useState<string | undefined>();
  const catalogs = useQuery({ queryKey: ['catalogs'], queryFn: ({ signal }) => loadCatalogs(signal) });
  const questions = useQuery({ queryKey: ['questions', subject, status, cursor], queryFn: ({ signal }) => api.request('get', '/api/v1/admin/questions', {
    signal, query: { per_page: 20, cursor, ...(subject ? { subject_id: subject } : {}), ...(status ? { status } : {}) },
  }) });
  return <><header className="page-heading"><div><span className="eyebrow">MERKEZİ İÇERİK</span><h1>Soru bankası</h1><p className="muted">Soruları hazırlayın, gözden geçirin ve yayımlayın.</p></div><Link className="button primary" to="/questions/new"><Icon name="plus" size={18} />Yeni soru</Link></header>
    <div className="overview"><div><span className="overview-icon"><Icon name="book" /></span><div><strong>{catalogs.data?.subjects.length ?? '—'}</strong><span>Ders</span></div></div><div><span className="overview-icon"><Icon name="grid" /></span><div><strong>{catalogs.data?.topics.length ?? '—'}</strong><span>Konu ve alt konu</span></div></div><div><span className="overview-icon"><Icon name="shield" /></span><div><strong>{catalogs.data?.['question-sources'].length ?? '—'}</strong><span>İçerik kaynağı</span></div></div><div className="overview-tip"><strong>Önce taslak, sonra yayın.</strong><span>Yeni düzenlemeler, yayımlanana kadar öğrencileri etkilemez.</span></div></div>
    {catalogs.isError && <ErrorNotice error={catalogs.error} retry={() => { void catalogs.refetch(); }} />}
    <section className="card question-table"><div className="table-toolbar"><div><h2>Tüm sorular</h2><span className="muted small-text">Bu sayfada {questions.data?.data.length ?? '—'} kayıt</span></div><div className="filters"><label><span>Ders filtresi</span><select aria-label="Ders filtresi" value={subject} onChange={(event) => { setSubject(event.target.value); setCursor(undefined); }}><option value="">Tüm dersler</option>{catalogs.data?.subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Yayın durumu</span><select aria-label="Yayın durumu" value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setCursor(undefined); }}><option value="">Tüm durumlar</option><option value="draft">Taslak</option><option value="published">Yayımlanmış</option></select></label></div></div>
      {questions.isPending ? <Loading text="Sorular yükleniyor…" /> : questions.isError ? <div className="table-padding"><ErrorNotice error={questions.error} retry={() => { void questions.refetch(); }} /></div> : !questions.data.data.length ? <div className="empty-state"><span className="empty-icon"><Icon name="book" size={30} /></span><h3>{subject || status ? 'Bu filtrelerde soru bulunamadı' : 'Soru bankanız hazır, ilk soruyu ekleyin'}</h3><p>{subject || status ? 'Filtreleri değiştirerek diğer soruları görebilirsiniz.' : 'Ders ve kaynağı belirleyin, soru taslağınızı oluşturun.'}</p>{subject || status ? <button className="button secondary" onClick={() => { setSubject(''); setStatus(''); setCursor(undefined); }}>Filtreleri temizle</button> : <Link className="button primary" to="/questions/new"><Icon name="plus" size={18} />İlk soruyu oluştur</Link>}</div> : <><div className="table-scroll"><table><thead><tr><th>Soru</th><th>Ders</th><th>Durum</th><th>Son düzenleme</th><th><span className="sr-only">İşlem</span></th></tr></thead><tbody>{questions.data.data.map((question) => <tr key={question.id}><td><Link className="question-link" to={`/questions/${question.id}`}>{question.latest_version.stem}</Link><span className="row-caption">Sürüm {question.latest_version.version}{question.latest_version.topic_id ? ` · ${catalogs.data?.topics.find((topic) => topic.id === question.latest_version.topic_id)?.name ?? 'Konu'}` : ''}</span></td><td>{catalogs.data?.subjects.find((item) => item.id === question.latest_version.subject_id)?.name ?? '—'}</td><td><Status published={question.status === 'published'} pending={question.has_pending_changes} /></td><td className="muted nowrap">{dateLabel(question.updated_at)}</td><td><Link className="icon-button" to={`/questions/${question.id}`} aria-label={`Düzenle: ${question.latest_version.stem}`}><Icon name="arrow" size={18} /></Link></td></tr>)}</tbody></table></div><div className="pagination"><span className="muted small-text">En fazla 20 soru / sayfa</span><div className="actions"><button className="button secondary small" disabled={!questions.data.links.prev} onClick={() => setCursor(cursorFromLink(questions.data.links.prev))}>Önceki</button><button className="button secondary small" disabled={!questions.data.links.next} onClick={() => setCursor(cursorFromLink(questions.data.links.next))}>Sonraki</button></div></div></>}
    </section></>;
}
